# Generated by Django 5.2.4 on 2025-08-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='steps',
        ),
        migrations.AddField(
            model_name='todo',
            name='ssteps',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
