# Generated by Django 5.2.4 on 2025-08-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_todo_steps_todo_ssteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='steps',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
