# Generated by Django 5.1.4 on 2024-12-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customerfeedback_survey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedback',
            name='survey_name',
            field=models.CharField(default='Default Survey Name', max_length=100),
        ),
    ]
