# Generated by Django 5.1.7 on 2025-04-24 10:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default=app.models.random_profile_pic, upload_to='profile_images'),
        ),
    ]
